domain_path: D:\tmp\daisyplus_lpddr4_b_25.1_250819\ws2\daisyplus\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
