domain_path: D:\sources\workspace\daisyplus_openssd_micron\daisyplus\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
