domain_path: D:\sources\CosmosPlus\2025.1\CosmosPlus_25.1_220717\ws\cosmosplus\export\cosmosplus\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
