domain_path: D:\tmp\daisyplus_lpddr4_b_25.1_250819\ws2\daisyplus\export\daisyplus\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
