#pragma once

#define XPAR_T4NFC_HLPER_0_BASEADDR 0
#define XPAR_T4NFC_HLPER_1_BASEADDR 0
#define XPAR_T4NFC_HLPER_2_BASEADDR 0
#define XPAR_T4NFC_HLPER_3_BASEADDR 0

#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_BASEADDR 0
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_BASEADDR 0
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_BASEADDR 0
