domain_path: D:\sources\CosmosPlus\2025.1\CosmosPlus_25.1_220717\ws\cosmosplus\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
